# Generated by Django 5.2.5 on 2025-09-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number_of_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='number_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
